# Generated by Django 2.2.6 on 2019-12-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20191203_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='eArrivalTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='eDepartureTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
